### ISSUE TITLE
Incompatible with tf.function (Tensor object has no attribute 'numpy')

### ISSUE THREAD

**Issue by jcrichard** [cvxgrp/cvxpylayers#56] opened 2020-05-15 09:05 UTC
Hi,

When I try to build a sequential model I get a compilation error. While I understand why it does not work I do not know how to fix it as it involves TF/keras. Is there a way to modify `CvxpyLayer` to make it work?

Reproducible example in tf 2.2:
```
from cvxpylayers.tensorflow import CvxpyLayer
import cvxpy as cp
import tensorflow as tf
from tensorflow.keras import layers

tf.keras.backend.set_floatx('float64')

class CustomLayer(layers.Layer):
   def __init__(self, input_dim, output_dim):
       super(CustomLayer, self).__init__()
       z = cp.Variable(output_dim)
       x = cp.Parameter(input_dim)
       problem = cp.Problem(cp.Minimize(
           cp.sum_squares(z -   x  )), [z >= 0 ])
       self.cvxpy_layer = CvxpyLayer(problem, [  x], [z])
   @tf.function
   def call(self, x):
      return self.cvxpy_layer( [x])[0]
 
tf.random.set_seed(0)
model = tf.keras.Sequential([
   CustomLayer(20, 20)])
model.build((300, 20))
```

Error raised:
```
AttributeError: in user code:

    <ipython-input-13-1b01fd49531e>:18 call  *
        return self.cvxpy_layer( [x])[0]
    /usr/local/lib/python3.6/dist-packages/cvxpylayers/tensorflow/cvxpylayer.py:124 __call__  *
        compute = tf.custom_gradient(
    /usr/local/lib/python3.6/dist-packages/cvxpylayers/tensorflow/cvxpylayer.py:154 _compute  *
        params = [p.numpy() for p in params]

    AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by akshayka** [comment] 2020-05-20 17:05
CvxpyLayer objects are not compatible with tf.function; they cannot be traced.

If you remove the tf.function decorator, your code should work.

I'll add this to the README documentation.

**Comment by jcrichard** [comment] 2020-05-20 17:10
Indeed it does and it is compatible with keras optimise. Thanks

**Comment by akshayka** [comment] 2020-05-20 17:22
Great! You're most welcome. I'll close this issue, then.

**Closed by akshayka** 2020-05-20 17:22 UTC

**Comment by franciscogaluppo** [comment] 2021-09-24 01:41
I can't reproduce OP's code on tf==2.6:

```python
class CustomLayer(Layer):
    def __init__(self, input_dim, output_dim):
        super(CustomLayer, self).__init__()
        z = cp.Variable(output_dim)
        x = cp.Parameter(input_dim)
        problem = cp.Problem(cp.Minimize(
            cp.sum_squares(z - x)), [z >= 0])
        self.cvxpy_layer = CvxpyLayer(problem, [x], [z])
    def call(self, x):
        return self.cvxpy_layer(x)[0]
    
tf.random.set_seed(0)
model = tf.keras.Sequential([
   CustomLayer(20, 20)])
model.build((300, 20))
```

Error raised:

```
AttributeError: in user code:

    <ipython-input-27-3a532f7163f3>:10 call  *
        return self.cvxpy_layer(x)[0]
    /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cvxpylayers/tensorflow/cvxpylayer.py:124 __call__  *
        compute = tf.custom_gradient(
    /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cvxpylayers/tensorflow/cvxpylayer.py:154 _compute  *
        params = [p.numpy() for p in params]
    /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:401 __getattr__
        self.__getattribute__(name)

    AttributeError: 'Tensor' object has no attribute 'numpy'
```

But I can reproduce the [ReLU](https://github.com/cvxgrp/cvxpylayers/blob/master/examples/tf/ReLU%20Layers.ipynb) example without any erros. I can't see what is different between the two that could raise the errors.

Further investigation showed me that if I use ```print(tf.executing_eagerly())``` inside the OP's call function, I get Falses, while in the ReLU call function it prints Trues. So there is something about these two codes that change the eager execution mode of the call functions. Do you know what could it be?

**Comment by aredder** [comment] 2024-11-03 15:50
> I can't reproduce OP's code on tf==2.6:
> 
> ```python
> class CustomLayer(Layer):
>     def __init__(self, input_dim, output_dim):
>         super(CustomLayer, self).__init__()
>         z = cp.Variable(output_dim)
>         x = cp.Parameter(input_dim)
>         problem = cp.Problem(cp.Minimize(
>             cp.sum_squares(z - x)), [z >= 0])
>         self.cvxpy_layer = CvxpyLayer(problem, [x], [z])
>     def call(self, x):
>         return self.cvxpy_layer(x)[0]
>     
> tf.random.set_seed(0)
> model = tf.keras.Sequential([
>    CustomLayer(20, 20)])
> model.build((300, 20))
> ```
> 
> Error raised:
> 
> ```
> AttributeError: in user code:
> 
>     <ipython-input-27-3a532f7163f3>:10 call  *
>         return self.cvxpy_layer(x)[0]
>     /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cvxpylayers/tensorflow/cvxpylayer.py:124 __call__  *
>         compute = tf.custom_gradient(
>     /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cvxpylayers/tensorflow/cvxpylayer.py:154 _compute  *
>         params = [p.numpy() for p in params]
>     /Users/----/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:401 __getattr__
>         self.__getattribute__(name)
> 
>     AttributeError: 'Tensor' object has no attribute 'numpy'
> ```
> 
> But I can reproduce the [ReLU](https://github.com/cvxgrp/cvxpylayers/blob/master/examples/tf/ReLU%20Layers.ipynb) example without any erros. I can't see what is different between the two that could raise the errors.
> 
> Further investigation showed me that if I use `print(tf.executing_eagerly())` inside the OP's call function, I get Falses, while in the ReLU call function it prints Trues. So there is something about these two codes that change the eager execution mode of the call functions. Do you know what could it be?

I run into the same issue with a custom layer.
